### ISSUE TITLE
Does it possible to run taxy webui on external interface instead of localhost?

### ISSUE THREAD

**Issue by zystem** [picoHz/taxy#21]
I mean without port forwarding, firewalling, and so on. Just set up some options and see taxy webui on 0.0.0.0

**Comment by picoHz** [comment]
WebUI is not intended to be directly exposed on the public network because its connection is not encrypted.

**Comment by picoHz** [comment]
As of v0.3.18, you can use the `--insecure-webui` flag to disable the secure cookie attribute. This allows you to log into the webui on an external interface via HTTP.

```bash
taxy start --insecure-webui
```
