### ISSUE TITLE
Traffic inspection

### ISSUE THREAD

**Issue by miraclx** [picoHz/taxy#22]
Are there any plans to bake in content inspection? - Track all requests, collecting stats like request time, size, etc. As well as viewing the request + response headers & bodies and the response status code.

Something like - https://mitmproxy.org/

On-the-fly mutation of headers would be nice too.. as https://github.com/svenstaro/proxyboi does, but with a much-nicer interface

Gotta say, I love the clean UI and its effortless config. There's lots of room to make this much more robust, it already has a nice foundation.

**Comment by picoHz** [comment]
I'm planning to add more detailed access logging and header rewriting features. However, I think Taxy may not be suitable for real-time inspection, unlike mitmproxy, as it is primarily designed for serving websites rather than for debugging.
