### ISSUE TITLE
how to set cert and key to start in HTTPS ?

### ISSUE THREAD

**Issue by nephaste** [picoHz/taxy#46]
Hi thanks a lot for this project

I am trying to create a qpkg for QNAP NAS and integrate it to our qpkg repository ( https://www.myqnap.org )

all is compiled fine and running with : 

./taxy start --webui 0.0.0.0:49492

but credential do not passed, seems due I need to go under HTTPS
also because I am on a headless NAS, localhost with --web-insecure do not help (need to force it on 0.0.0.0)

Unfortunately, I can't find a way to force ssl and run on https on 0.0.0.0:49492 

Any chance to get this option, adding my certs and key file to command line to be able to manage it locally over https ?

Thanks a lot for your help,

**Comment by picoHz** [comment]
Hello Stéphane.

> but credential do not passed, seems due I need to go under HTTPS
> also because I am on a headless NAS, localhost with --web-insecure do not help (need to force it on 0.0.0.0)

I can't figure out what you want to do here.
You can simply access port 49492 from a web browser using HTTP. The headless NAS has nothig to do with this.
How did you open the WebUI? What browser do you use?

**Comment by nephaste** [comment]
Hello

Listen with --insecure-web listen to localhost opening a browser on my computer pointing to NAS ip and port 46492 won't display the web page... using --webui 0.0.0.0:46492 display the web page credential (user is added previously) but entering credential, is in loop and can't by pass credential request... (look like i need https) according the setup guide and after reading : 

https://github.com/picoHz/taxy/issues/2

i am searching to make listen  --webui 0.0.0.0:46492 over https and not http, but I can provide a cert and key file in command line flag, to administrate Taxy on my LAN

hope i am clear :)

**Comment by picoHz** [comment]
> Listen with --insecure-web listen to localhost opening a browser on my computer pointing to NAS ip and port 46492 won't display the web page... using --webui 0.0.0.0:46492 display the web page credential (user is added previously) but entering credential, is in loop and can't by pass credential request...

You need to specify `--insecure-webui` and `--webui` together like this:

```
taxy start --insecure-webui --webui 0.0.0.0:46492
```

**Comment by nephaste** [comment]
I feel stupid, thanks a lot  :)
