### ISSUE TITLE
Redirect option HTTP to HTTPS

### ISSUE THREAD

**Issue by Gamerboy59** [picoHz/taxy#75]
Using this as a reverse web proxy, is there any configuration (per port, proxy or in general for http/https) to redirect from http to https automatically?

**Comment by picoHz** [comment]
There is no such option yet to automatically redirect to HTTPS.
Thank you for the suggestion.

**Comment by picoHz** [comment]
@Gamerboy59 As of v0.3.33, Taxy automatically redirects HTTP to HTTPS when possible. 
You can opt out in the per-proxy options.
