### ISSUE TITLE
Add compiled BSD release builds

### ISSUE THREAD

**Issue by Gamerboy59** [picoHz/taxy#77]
Right now there are releases available here at Github for Apple, Windows and Linux. Installing on FreeBSD myself with Cargo is working fine. Can you please add compiled releases that are executable on BSD distros like FreeBSD, too?

**Comment by picoHz** [comment]
I tried to cross-compile for FreeBSD on github actions but got a link error.
I'm not sure if it is possible to build a FreeBSD binary on Github actions.

**Comment by picoHz** [comment]
@Gamerboy59 Thank you for the information. 
I tried freebsd-vm, and it works quite well. FreeBSD builds are now available!
