### ISSUE TITLE
Host Regexp

### ISSUE THREAD

**Issue by almereyda** [picoHz/taxy#78]
Currently globbing for `*.*.localdomain` or inserting `(.*).localdomain` does not allow to reach the host `localhome.localhost.localdomain`.

It could be nice to define Hosts with Regular Expressions, in so multiple levels of subdomains are supported.

**Comment by picoHz** [comment]
@almereyda  Thank you for your suggestion!
Taxy supports regex patterns in virtual hosts starting with v0.3.34.
