### ISSUE TITLE
502 Bad gateway

### ISSUE THREAD

**Issue by the-moog** [picoHz/taxy#85]
I've been having a problem where some apps forward properly but others do not. Returning Bad Gateway 502. I think this may be related to missing headers.   Can you confirm that Taxy adds the  X-Forwarded-For and X-Forwarded-Proto headers? I looked but could not find a configuration option to turn that on.

**Comment by picoHz** [comment]
I've fixed some inconsistent behavior with the x-forwarded-* headers in v0.3.31. 
Feel free to reopen the issue if the error persists.
