### ISSUE TITLE
UDP support

### ISSUE THREAD

**Issue by fbettag** [picoHz/taxy#87]
Hey man, awesome project. I have just replaced a very cumbersome traefik/haproxy setup and the only thing missing to make this better than the both of them would be UDP forwarding.

Any plans on this feature?

**Comment by picoHz** [comment]
@fbettag Thank you for your suggestion! 
Taxy supports UDP proxy mode starting with v0.3.32.

**Comment by fbettag** [comment]
awesome! thank you!
